:sparkles: Add run_demo e2e test (#469)
* :bug: share analysis step for validation, add pre_flight_checks

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :ghost: make incident store config optional

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :sparkles: fix up build spec for VCR and add steps to run e2e test

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :bug: do not apply diff again

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :ghost: add debug task to gh action

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :ghost: download maven index from container

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :ghost: temporarily remove datas directory

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :ghost: add pydantic to hidden imports

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :bug: setup java

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :ghost: setup java distribution

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :ghost: remove vcr dir

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :sparkles: implement custom cache for model provider

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :ghost: update action with the actual test

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :sparkles: add meta-llama-70b responses

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :bug: fix unit tests

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :sparkles: update cache responses

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :bug: fix cache

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* update expected output

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :bug: update expected output

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* :bug: only check number of files changed

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

---------

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

diff --git a/.github/workflows/build-and-push-binaries.yml b/.github/workflows/build-and-push-binaries.yml
--- a/.github/workflows/build-and-push-binaries.yml
+++ b/.github/workflows/build-and-push-binaries.yml
@@ -31,10 +31,19 @@ jobs:
             shell: bash
           - os: windows-latest
             shell: cmd
+        models:
+          - provider: ChatIBMGenAI
+            model_id: meta-llama/llama-3-70b-instruct
+            max_new_tokens: 2048
     runs-on: ${{ matrix.runs_on.os }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+
+      - uses: actions/setup-java@v3
+        with:
+          distribution: "oracle"
+          java-version: '17'
 
       - id: release_info
         uses: joutvhu/get-release@v1
@@ -71,16 +80,65 @@ jobs:
 
       - name: Build RPC server
         run: |
-          pip install -r requirements.txt
           pip install pyinstaller
           pip install -e .
+          pip install -r requirements.txt
           pyinstaller build/build.spec
+        env:
+          PATH: ${{ env.PATH }}
 
       - name: Build Kai Analyzer
         run: |
           cd kai_analyzer_rpc && go build -ldflags="-extldflags=-static" -o kai-analyzer-rpc main.go && cd ..
 
-# Tasks below will only happen when this action is dispatched to publish a release.
+      - name: Setup analysis deps
+        if: matrix.runs_on.os == 'ubuntu-latest'
+        run: |
+          cp ./dist/kai-rpc-server ./example/analysis/
+          cp ./kai_analyzer_rpc/kai-analyzer-rpc ./example/analysis/
+          docker run -d --name=bundle quay.io/konveyor/jdtls-server-base:latest
+          docker cp bundle:/usr/local/etc/maven.default.index ./example/analysis
+          docker cp bundle:/jdtls ./example/analysis
+          docker cp bundle:/jdtls/java-analyzer-bundle/java-analyzer-bundle.core/target/java-analyzer-bundle.core-1.0.0-SNAPSHOT.jar ./example/analysis/bundle.jar
+          docker cp bundle:/usr/local/etc/maven.default.index ./example/analysis
+          git config --global user.email "no-reply@konveyor.io"
+          git config --global user.name "Konveyor CI"
+          git clone https://github.com/konveyor/rulesets
+          mv ./rulesets/default/generated ./example/analysis/rulesets
+          
+          cat << EOF > ./example/config.toml
+          [models]
+          provider = "${{ matrix.models.provider }}"
+          [models.args]
+          model_id = "${{ matrix.models.model_id }}"
+          EOF
+          
+          if [[ -n "${{ matrix.models.max_new_tokens }}" ]]; then
+          cat << EOF >> ./example/config.toml
+          parameters.max_new_tokens = ${{ matrix.models.max_new_tokens }}
+          EOF
+          fi
+
+      - name: Run e2e test
+        if: matrix.runs_on.os == 'ubuntu-latest' 
+        run: |
+          which python
+          cd example
+          ./fetch.sh
+          ./run_demo.py
+          cd coolstore
+          changed_files_count=$(git diff --name-only | wc -l)
+          if (( changed_files_count == 26 )); then
+            echo "Tests failed"
+            exit 1
+          else
+            echo "Tests passed"
+          fi
+        env:
+          PATH: ${{ env.PATH }}
+          GENAI_KEY: "BWAHAHA"
+      
+#   Tasks below will only happen when this action is dispatched to publish a release.
 
       - name: lowercase runner.os (linux & mac)
         if: matrix.runs_on.os != 'windows-latest' && github.event_name == 'workflow_dispatch'
