:bug: Clean environement of pyinstaller changes for DYLD_LIBRARY_PATH and DLLDirectory (#543)
* fixing bug where validator was not setting the violation id for tasks

Signed-off-by: Shawn Hurley <shawn@hurley.page>

* Adding environment cleaning for pyinstaller

Signed-off-by: Shawn Hurley <shawn@hurley.page>

* adding full e2e tests on windows and mac

writing powershell script for running e2e testsf

Signed-off-by: Shawn Hurley <shawn@hurley.page>

* install git on windows 11 arm
bumping tree sitter java for install to work on windows-11-arm
install compiler for windows 11

Signed-off-by: Shawn Hurley <shawn@hurley.page>

Signed-off-by: Shawn Hurley <shawn@hurley.page>

Signed-off-by: Shawn Hurley <shawn@hurley.page>

* removing windows 11 and trying to find maven for windows

Signed-off-by: Shawn Hurley <shawn@hurley.page>

* Fixing sorting of tasks to be deterministic

* Adding __lt__ method for analyzer validation errors for sorting

Signed-off-by: Shawn Hurley <shawn@hurley.page>

* adding cache data for sorted tasks

removing windows 11 and trying to find maven for windows

Signed-off-by: Shawn Hurley <shawn@hurley.page>

* add maven to path and use shutil to find right binary

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

* fixing two bugs

Signed-off-by: Shawn Hurley <shawn@hurley.page>

* temporarily remove windows tests while we take the time to debug

Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>

---------

Signed-off-by: Shawn Hurley <shawn@hurley.page>
Signed-off-by: Pranav Gaikwad <pgaikwad@redhat.com>
Co-authored-by: Pranav Gaikwad <pgaikwad@redhat.com>

diff --git a/.github/workflows/build-and-push-binaries.yml b/.github/workflows/build-and-push-binaries.yml
--- a/.github/workflows/build-and-push-binaries.yml
+++ b/.github/workflows/build-and-push-binaries.yml
@@ -29,15 +29,17 @@ on:
 
 # the build matrix exists as an env var so that we can
 # share that info reliably with the "calling" workflow
+# TODO: removing  { "os": "windows-11-preview-arm", "shell": "cmd" }, from the matrix
+# we have to wait for the a real image to be published that actually has what we
+# need to use it. This wil be fine for now.
 env:
   BUILD_MATRIX: | 
     [ 
       { "os": "ubuntu-latest", "shell": "bash" },
       { "os": "macos-latest", "shell": "bash" },
       { "os": "macos-13", "shell": "bash" },
-      { "os": "windows-latest", "shell": "cmd" },
-      { "os": "windows-11-preview-arm", "shell": "cmd" },
-      { "os": "ubuntu-24.04-arm", "shell": "bash" }
+      { "os": "ubuntu-24.04-arm", "shell": "bash" },
+      { "os": "windows-latest", "shell": "cmd" }
     ]
 jobs:
   # these are specific java artifacts (cross-platform) that we
@@ -87,14 +89,46 @@ jobs:
     - download_artifacts
     name: Run e2e test
     strategy:
+      #fail-fast: false
       matrix:
         runs_on: ${{ fromJson(needs.share_matrix_info.outputs.matrix_info) }}
         models:
-          - provider: ChatIBMGenAI
-            model_id: meta-llama/llama-3-1-70b-instruct
-            max_new_tokens: 2048
+          - provider: ChatOpenAI
+            model_id: kai-test-generation
     runs-on: ${{ matrix.runs_on.os }}
     steps:
+      # Keeping these steps, because if we must, we may need to use them to get arm builds for windows.
+      - name: Download Git for Windows (aarch64)
+        uses: robinraju/release-downloader@v1
+        if: ${{ matrix.runs_on.os == 'windows-11-preview-arm'}}
+        with:
+          repository: "git-for-windows/git"
+          tag: "v2.48.0-rc1.windows.1"
+          filename: "Git-2.48.0-rc1-arm64.exe"
+
+      - name: Install Git for Windows (aarch64)
+        if: ${{ matrix.runs_on.os == 'windows-11-preview-arm'}}
+        run: |
+          Start-Process -FilePath "Git-2.48.0-rc1-arm64.exe" -ArgumentList "/VERYSILENT" -NoNewWindow -Wait
+          Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\Git\cmd" -Encoding utf8
+          Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\Git\bin" -Encoding utf8
+
+      - name: install windows compilers
+        if: ${{ matrix.runs_on.os == 'windows-11-preview-arm'}}
+        run: |
+          Set-ExecutionPolicy Bypass -Scope Process
+          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) 
+          echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+          choco feature enable -n allowGlobalConfirmation
+          choco install visualstudio2022-workload-vctools --package-parameters "--includeOptional"
+          choco install -y llvm
+          Get-ChildItem -Path "C:\Program Files\LLVM\bin" -ErrorAction Ignore
+          Get-ChildItem -Path "C:\Program Files (x86)\LLVM\bin" -ErrorAction Ignore
+          & "C:\Program Files\LLVM\bin\clang.exe" --version
+          Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\LLVM\bin" -Encoding utf8
+          Set-Alias -Name clang -Value "C:\Program Files\LLVM\bin\clang.exe"
+          clang --version
+      
       - name: Checkout code
         uses: actions/checkout@v3
         with:
@@ -111,6 +145,20 @@ jobs:
         with:
           distribution: "microsoft"
           java-version: "17"
+
+      - name: Set up Maven
+        if: ${{ startsWith(matrix.runs_on.os, 'windows') }}
+        uses: stCarolas/setup-maven@v5
+        with:
+          maven-version: 3.9.9
+
+      - name: Add things to path
+        if: ${{ startsWith(matrix.runs_on.os, 'windows') }}
+        run: |
+          Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\Git\cmd" -Encoding utf8
+          Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\Git\bin" -Encoding utf8
+          Add-Content -Path $env:GITHUB_PATH -Value "C:\hostedtoolcache\windows\maven\3.9.9\x64\bin" -Encoding utf8
+          Add-Content -Path $env:GITHUB_ENV -Value "Path=$env:Path;C:\hostedtoolcache\windows\maven\3.9.9\x64\bin" -Encoding utf8
 
       - id: release_info
         if: ${{ github.event.inputs.publish_artifacts_to_release || false }}
@@ -131,13 +179,6 @@ jobs:
         with:
           go-version: "1.23"
           check-latest: true
-
-      - name: Set up venv (windows)
-        if: ${{ startsWith(matrix.runs_on.os, 'windows') }}
-        run: |
-          python -m venv venv
-          . venv\Scripts\activate
-          echo PATH=$PATH >> $GITHUB_ENV
 
       - name: Set up venv (linux & mac)
         if: ${{ ! startsWith(matrix.runs_on.os, 'windows') }}
@@ -179,17 +220,80 @@ jobs:
         if: ${{ startsWith(matrix.runs_on.os, 'windows') }}
         run: |
           Expand-Archive -Path java-deps.zip -DestinationPath java-deps
+          Copy-Item -Verbose -Path .\java-deps\* -Destination .\example\analysis -Recurse
 
       - name: Run e2e test
-        if: ${{ startsWith(matrix.runs_on.os, 'ubuntu') }}
+        if: false # ${{ startsWith(matrix.runs_on.os, 'windows') }}
+        run: |
+          git config --global user.email "no-reply@konveyor.io"
+          git config --global user.name "Konveyor CI"
+
+          cp ./dist/kai-rpc-server.exe ./example/analysis/
+          cp ./kai_analyzer_rpc/kai-analyzer-rpc ./example/analysis/
+
+          Remove-Item -Path .\example\initialize.toml
+
+          New-Item -Path ".\example\initialize.toml" -ItemType File -Value @"
+          root_path = "./coolstore"
+          analyzer_lsp_java_bundle_paths = [ "./analysis/bundle.jar" ]
+          analyzer_lsp_lsp_path = "./analysis/jdtls/bin/jdtls"
+          analyzer_lsp_rpc_path = "./analysis/kai-analyzer-rpc"
+          analyzer_lsp_rules_paths = [ "./analysis/rulesets/default/generated" ]
+          analyzer_lsp_dep_labels_path = "./analysis/maven.default.index"
+
+          demo_mode = true
+          enable_reflection = false
+
+          [log_config]
+          log_level = "info"
+          file_log_level = "debug"
+          log_dir_path = '${{github.workspace}}\logs\'
+
+          [model_provider]
+          provider = "${{ matrix.models.provider }}"
+          [model_provider.args]
+          model = "${{ matrix.models.model_id }}"
+          
+          "@
+
+          if ("${{ matrix.models.max_new_tokens }}") {
+            Add-Content -Path ".\example\initialize.toml" -Value "parameters.max_new_tokens = ${{ matrix.models.max_new_tokens }}"
+          }
+          
+          Get-Content -Path .\example\initialize.toml
+
+          Get-Command python
+          Set-Location -Path .\example
+
+          git clone https://github.com/konveyor-ecosystem/coolstore.git
+          pip list 
+          python run_demo.py
+          cd coolstore
+          $changed_files_count = (git diff --name-only | Measure-Object).Count
+          if ($changed_files_count -eq 26) {
+            echo "Tests passed"
+            exit 0
+          } 
+          else {
+            echo "Tests failed, only $changed_files_count where changed"
+            git diff --name-only
+            cat ../../logs/kai_server.log
+            cat ../../logs/kai_server.log
+            exit 1
+          }
+        env:
+          GENAI_KEY: "BWAHAHA"
+          OPENAI_API_KEY: "BWAHAHA"
+
+
+      - name: Run e2e test
+        if: ${{ ! startsWith(matrix.runs_on.os, 'windows') }}
         run: |
           git config --global user.email "no-reply@konveyor.io"
           git config --global user.name "Konveyor CI"
 
           cp ./dist/kai-rpc-server ./example/analysis/
           cp ./kai_analyzer_rpc/kai-analyzer-rpc ./example/analysis/
-
-          rm -f ./example/initialize.toml
 
           cat << EOF > ./example/initialize.toml
           root_path = "./coolstore"
@@ -203,14 +307,15 @@ jobs:
           enable_reflection = false
 
           [log_config]
-          log_level = "debug"
+          log_level = "info"
           file_log_level = "debug"
-          log_dir_path = "/home/runner/work/kai/kai/kai/../../logs/"
-
+          log_dir_path = "${{github.workspace}}/logs/"
+          
           [model_provider]
           provider = "${{ matrix.models.provider }}"
+         
           [model_provider.args]
-          model_id = "${{ matrix.models.model_id }}"
+          model = "${{ matrix.models.model_id }}"
           EOF
 
           if [[ -n "${{ matrix.models.max_new_tokens }}" ]]; then
@@ -232,13 +337,14 @@ jobs:
           else
             echo "Tests failed, only $changed_files_count where changed"
             git diff --name-only
-            cat /home/runner/work/kai/kai/kai/../../logs/kai_server.log
-            cat /home/runner/work/kai/kai/example/logs/kai_server.log
+            cat ../../logs/kai_server.log
+            cat ../../logs/kai_server.log
             exit 1
           fi
         env:
           PATH: ${{ env.PATH }}
           GENAI_KEY: "BWAHAHA"
+          OPENAI_API_KEY: "BWAHAHA"
 
       - name: lowercase runner.os (linux & mac)
         if: ${{ ! startsWith(matrix.runs_on.os, 'windows') }}
